package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_STATUS extends EnumerationDescriptorBase {

  public EnumerationDescriptor_STATUS() {
    super(0x21222a0d7ed14311L, 0xa572182d14b72a71L, 0x671ab00d8527da89L, "STATUS", "r:ca92aa82-bfce-4b0d-80de-e13164636220(ArduinoML.structure)/7429444107416099465", PrimitiveTypeId.BOOLEAN);
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_true_0 = new EnumerationDescriptor.MemberDescriptor("true", "high", "r:ca92aa82-bfce-4b0d-80de-e13164636220(ArduinoML.structure)/7429444107416099467", "high");
  private final EnumerationDescriptor.MemberDescriptor myMember_false_0 = new EnumerationDescriptor.MemberDescriptor("false", "low", "r:ca92aa82-bfce-4b0d-80de-e13164636220(ArduinoML.structure)/7429444107416099466", "low");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x21222a0d7ed14311L, 0xa572182d14b72a71L, 0x671ab00d8527da89L, 0x671ab00d8527da8bL, 0x671ab00d8527da8aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_true_0, myMember_false_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "true":
        return myMember_true_0;
      case "false":
        return myMember_false_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
